### ISSUE TITLE
Love the extension! Do you know how to exclude subdomains from urls in content-blockers?

### ISSUE THREAD

**Issue by Daniyaldehleh** [ProgrammerFaraz/AdBlocker#1]
Hi there,

Hope you’re doing well,

Do you know how to exclude the subdomains from urls in content blockers?

Like: Block "www.youtube.com" but not "https://www.youtube.com/results?search_query". I've tried using "ignore-previous-rules" & regex but none seem to be working.

Thanks,
Daniyal

**Comment by ProgrammerFaraz** [comment]
Hi Daniyal,

Hope you're doing good.

That's not a subdomain you're trying to exclude. A subdomain would be something like subdomain.youtube.com if the parent domain was youtube.com
What comes after the / is just a directory on the host.

You could potentially exclude a subdomain, but that's not what you're trying to do. You're trying to exclude a small subsection of a single domain. Try doing this for subdomain and directory:

Sometimes you only want users to be able to access certain parts of a website/domain. Keep in mind that the allow list will always override the block list (including category blocks).

Let’s say you want users to be able to access [docs.google.com](http://docs.google.com/) (a subdomain), but not [Google.com](http://google.com/) (a domain) or any other Google subdomains (such as [sheets.google.com](http://sheets.google.com/)):

Add “[google.com](http://google.com/)" to your block list (this will also block all subdomains)
Add “[docs.google.com](http://docs.google.com/)” to your allow list (this will override the block list for this subdomain only)

Try doing this for directory as well, hope this helps.

Thanks,
Faraz

**Comment by Daniyaldehleh** [comment]
Hi Faraz!

Thanks a lot for your thorough response, 

You're right. I meant to say path & not subdomain. May I know what you mean by allow list or where I can find it?

I am assuming by lock list, you mean the "if-domain" ket in blockers.json

**Comment by ProgrammerFaraz** [comment]
Try using this: 

You start by blocking every domain you want to block and then adding this for specific domain that you want to add to whitelist/allowed list.

`{
    "trigger": {
        "url-filter": ".*",
        "if-domain": ["Google.com"]
    },
    "action": {
        "type": "ignore-previous-rules"
    } 
}`

**Comment by Daniyaldehleh** [comment]
didn't do the job, just like with: 
https://stackoverflow.com/questions/40557203/ios-safari-content-blocker-ignore-previous-rules-not-working

**Comment by ProgrammerFaraz** [comment]
Check this answer on stackoverflow:

https://stackoverflow.com/questions/32975416/ios-content-blocker-whitelist-website
